//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBAOCAOCONGNODAILY
    {
        public string MaCTBCCNDL { get; set; }
        public string MaBCCNDL { get; set; }
        public int NoDau { get; set; }
        public int NoCuoi { get; set; }
        public int PhatSinh { get; set; }
    }
}
