//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class daiLyCacheEntities : DbContext
    {
        public daiLyCacheEntities()
            : base("name=daiLyCacheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAOCONGNODAILY> BAOCAOCONGNODAILies { get; set; }
        public virtual DbSet<CTBAOCAOCONGNODAILY> CTBAOCAOCONGNODAILies { get; set; }
        public virtual DbSet<CTBAOCAODOANHSO> CTBAOCAODOANHSOes { get; set; }
        public virtual DbSet<CTPHIEUTHUTIEN> CTPHIEUTHUTIENs { get; set; }
        public virtual DbSet<CTPHIEUXUATHANG> CTPHIEUXUATHANGs { get; set; }
        public virtual DbSet<DAILY> DAILies { get; set; }
        public virtual DbSet<LOAIDAILY> LOAIDAILies { get; set; }
        public virtual DbSet<LOAIMATHANG> LOAIMATHANGs { get; set; }
        public virtual DbSet<MATHANG> MATHANGs { get; set; }
        public virtual DbSet<PHIEUTHUTIEN> PHIEUTHUTIENs { get; set; }
        public virtual DbSet<PHIEUTHUTIENNO> PHIEUTHUTIENNOes { get; set; }
        public virtual DbSet<PHIEUXUATHANG> PHIEUXUATHANGs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BAOCAODOANHSO> BAOCAODOANHSOes { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
    }
}
