//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG
    {
        public string MaHang { get; set; }
        public string MaLoaiHang { get; set; }
        public string TenMatHang { get; set; }
        public string LoaiHang { get; set; }
        public string DonViTinh { get; set; }
        public int DonGia { get; set; }
    
        public virtual LOAIMATHANG LOAIMATHANG { get; set; }
    }
}
