//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIENNO
    {
        public string MaPTTN { get; set; }
        public string MaDaiLy { get; set; }
        public string MaThuTien { get; set; }
        public int SoTienThu { get; set; }
        public int TienConLai { get; set; }
    }
}
