//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHUTIEN
    {
        public string MaThuTien { get; set; }
        public string MaXuatHang { get; set; }
        public string MaDaiLy { get; set; }
        public string TenDaiLy { get; set; }
        public string MaLoaiDL { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string Quan { get; set; }
        public System.DateTime NgayThuTien { get; set; }
    }
}
