//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUATHANG
    {
        public string MaXuatHang { get; set; }
        public string MaHang { get; set; }
        public string TenMatHang { get; set; }
        public string DonViTinh { get; set; }
        public int SoLuong { get; set; }
        public int DonGia { get; set; }
        public int ThanhTien { get; set; }
        public System.DateTime NgayLapPhieu { get; set; }
        public int TongTien { get; set; }
        public int SoTienTra { get; set; }
        public int TienNo { get; set; }
    }
}
