//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int DLToiDa { get; set; }
        public int TNToiDa1 { get; set; }
        public int TNToiDa2 { get; set; }
    }
}
